# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      # - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      - image: circleci/node:8.11.3
      - image: mongo:3.4.4

    working_directory: ~/repo
    
    steps:
      - checkout
    
      - run: echo "hello Jewel :)"
      
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: install-npm-wee
          command: npm install
     
      - run:
          npm install mocha chai --save-dev
          
      - run:
          npm install --user -g mocha
      
      - run:
          npm install jsdom
          
      - run: 
          npm test

      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
